version: '3'

services:
  app:
    build: .
    ports:
      - "5050:5050"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/xyzuniversity
    depends_on:
      - mongodb
    restart: always
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=qwerty
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
